In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from data import Data
from brutforce import Brutforce
from visualizer import Visualizer
from average_approximation import AverageApproximation
from approximation import Approximation
from half_approximation import HalfApproximation

In [3]:
num_bells = 3
num_teams = 6
T = 15
data = Data(T=T, num_bells=num_bells, num_teams=num_teams, seed=8, team_limit=5)

# print(data.plane_services)
for line in data.plane_services:
    print([int(x) for x in line])

print([sum(line) for line in data.plane_services])

[5, 4, 4, 2]
[1, 1, 3, 1]
[4, 1, 2, 3]
[3, 3, 2, 4]
[5, 4, 6]
[5, 4, 2, 4]
[15, 6, 10, 12, 15, 15]


In [40]:
bruteforce = HalfApproximation(data)
sol = bruteforce.solve()

print(sol[0])
print(sol[1])
print(sol[2])

59.0
[[1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0.]]
[7, 8, 12]


In [45]:
import numpy as np

bell = 6
np.sum(sol[1][:, 0:bell]) / ((bell) * data.num_teams)

0.6388888888888888

In [48]:
(6 * 6 - 13) / (7 * 6)

0.5476190476190477